In [2]:
# Importing pandas
import pandas as pd

In [3]:
# Load the Economic Freedom Index data
freedom_index_df = pd.read_excel('economic-freedom-of-the-world-2024-master-index-data-for-researchers-iso.xlsx', header=4)

In [4]:
freedom_index_df.head()

,Unnamed: 0,Year,ISO Code 2,ISO Code 3,Countries,Economic Freedom Summary Index,Rank,Quartile,Government consumption,data,...,Tax compliance,Business regulations,Market openness,Business Permits,Distorton of the business environment,Freedom to enter markets and compete,Regulation,Area 5 Rank,World Bank Region,"World Bank Current Income Classification, 1990-Present"
0,NaN,2022.0,AL,ALB,Albania,7.48,38.0,1.0,8.282353,11.84,...,3.587625,5.379721,6.810619,5.621940,6.250000,6.227520,6.897016,55.0,Europe & Central Asia,UM
1,NaN,2022.0,DZ,DZA,Algeria,4.46,161.0,4.0,3.491176,28.13,...,4.764764,3.841924,4.641448,8.771111,2.583207,5.331922,4.508463,156.0,Middle East & North Africa,LM
2,NaN,2022.0,AO,AGO,Angola,4.79,155.0,4.0,7.944118,12.99,...,4.641462,4.443797,3.427185,7.916416,1.250000,4.197867,5.302379,140.0,Sub-Saharan Africa,LM
3,NaN,2022.0,AR,ARG,Argentina,4.55,159.0,4.0,6.167647,19.03,...,4.504147,4.969248,6.144822,5.726521,3.380395,5.083913,4.804769,148.0,Latin America & the Caribbean,UM
4,NaN,2022.0,AM,ARM,Armenia,7.49,36.0,1.0,7.058824,16.00,...,6.020369,5.566860,5.590883,9.302574,5.000000,6.631152,7.095430,45.0,Europe & Central Asia,UM

In [5]:
# Drop 'ISO Code 2' column and rename 'ISO Code 3' to 'Country Name'
freedom_index_df = freedom_index_df.drop(columns=['ISO Code 2'])
freedom_index_df = freedom_index_df.rename(columns={'ISO Code 3': 'Country Name'})

In [6]:
# Making sure we only have the required columns for the base dataset i.e Economic Freedom Index
req_columns_free = ['Year','Countries',' Economic Freedom Summary Index']
freedom_index_df = freedom_index_df[req_columns_free]

In [7]:
freedom_index_df.head()

     Year  Countries   Economic Freedom Summary Index
0  2022.0    Albania                             7.48
1  2022.0    Algeria                             4.46
2  2022.0     Angola                             4.79
3  2022.0  Argentina                             4.55
4  2022.0    Armenia                             7.49

In [8]:
# Rename the ' Economic Freedom Summary Index' to 'Economic Freedom Index'
freedom_index_df = freedom_index_df.rename(columns={' Economic Freedom Summary Index':'Economic Freedom Index'})

In [9]:
# Display rows with missing 'Year' values
rows_with_nan = freedom_index_df[freedom_index_df['Year'].isna()]
print("Rows with missing 'Year':")
print(rows_with_nan)

# Drop rows with missing 'Year'
freedom_index_df = freedom_index_df.dropna(subset=['Year'])

Rows with missing 'Year':
      Year Countries  Economic Freedom Index
4785   NaN       NaN                     NaN

In [10]:
# Change the datatype of Year column to int
freedom_index_df['Year'] = freedom_index_df['Year'].astype(int)

In [11]:
# Filter the DataFrame for the specified year range i.e 2015-2022

freedom_index_df = freedom_index_df[(freedom_index_df['Year']>=2015) & (freedom_index_df['Year']<=2022)]

In [12]:
freedom_index_df.head()

   Year  Countries  Economic Freedom Index
0  2022    Albania                    7.48
1  2022    Algeria                    4.46
2  2022     Angola                    4.79
3  2022  Argentina                    4.55
4  2022    Armenia                    7.49

In [13]:
# Checking the number of null values in the base dataset
freedom_index_df.isna().sum()

Year                      0
Countries                 0
Economic Freedom Index    8
dtype: int64

In [14]:
# Checking what and where the missing values are
freedom_index_df[freedom_index_df['Economic Freedom Index'].isna()]

      Year Countries  Economic Freedom Index
796   2018   Somalia                     NaN
961   2017   Somalia                     NaN
1024  2016   Comoros                     NaN
1033  2016  Djibouti                     NaN
1126  2016   Somalia                     NaN
1189  2015   Comoros                     NaN
1198  2015  Djibouti                     NaN
1291  2015   Somalia                     NaN

In [15]:
# Dropping the rows where there are null values
freedom_index_df.dropna(inplace=True)

In [16]:
freedom_index_df.head()

   Year  Countries  Economic Freedom Index
0  2022    Albania                    7.48
1  2022    Algeria                    4.46
2  2022     Angola                    4.79
3  2022  Argentina                    4.55
4  2022    Armenia                    7.49

In [17]:
# Sort the dataset so that it looks neat and organized
freedom_index_df = freedom_index_df.sort_values(by=['Year','Countries']).reset_index(drop=True)

In [18]:
freedom_index_df.head()

   Year  Countries  Economic Freedom Index
0  2015    Albania                    7.64
1  2015    Algeria                    4.68
2  2015     Angola                    5.25
3  2015  Argentina                    4.95
4  2015    Armenia                    7.43

In [19]:
# Group by 'Year' and find the country with the highest 'Economic Freedom Index' for each year
highest_freedom_index_df = freedom_index_df.loc[freedom_index_df.groupby('Year')['Economic Freedom Index'].idxmax()]

# Reset the index for better readability
highest_freedom_index_df = highest_freedom_index_df.reset_index(drop=True)

highest_freedom_index_df

   Year             Countries  Economic Freedom Index
0  2015  Hong Kong SAR, China                    9.02
1  2016  Hong Kong SAR, China                    9.02
2  2017  Hong Kong SAR, China                    9.05
3  2018  Hong Kong SAR, China                    9.05
4  2019  Hong Kong SAR, China                    8.92
5  2020  Hong Kong SAR, China                    8.65
6  2021  Hong Kong SAR, China                    8.61
7  2022  Hong Kong SAR, China                    8.58

In [20]:
# Renaming Hong Kong for better readibility in the highest_freedom_index_df
highest_freedom_index_df['Countries'] = highest_freedom_index_df['Countries'].replace('Hong Kong SAR, China', 'Hong Kong')

In [21]:
highest_freedom_index_df

   Year  Countries  Economic Freedom Index
0  2015  Hong Kong                    9.02
1  2016  Hong Kong                    9.02
2  2017  Hong Kong                    9.05
3  2018  Hong Kong                    9.05
4  2019  Hong Kong                    8.92
5  2020  Hong Kong                    8.65
6  2021  Hong Kong                    8.61
7  2022  Hong Kong                    8.58

In [22]:
# Renaming Hong Kong for better readibility in the freedom_index_df
freedom_index_df['Countries'] = freedom_index_df['Countries'].replace('Hong Kong SAR, China', 'Hong Kong')

In [23]:
# Sort the top 15 countries with the highest 'Economic Freedom Index' for the year 2022
freedom_index_df_top_15_2022 = freedom_index_df[freedom_index_df['Year']==2022].sort_values(by='Economic Freedom Index',ascending=False).iloc[:15].reset_index(drop=True)

In [24]:
freedom_index_df_top_15_2022

    Year       Countries  Economic Freedom Index
0   2022       Hong Kong                    8.58
1   2022       Singapore                    8.55
2   2022     Switzerland                    8.43
3   2022     New Zealand                    8.39
4   2022   United States                    8.09
5   2022         Denmark                    8.02
6   2022         Ireland                    8.02
7   2022          Canada                    7.99
8   2022      Luxembourg                    7.98
9   2022       Australia                    7.98
10  2022           Japan                    7.90
11  2022  United Kingdom                    7.88
12  2022         Finland                    7.87
13  2022         Iceland                    7.84
14  2022           Malta                    7.82

In [ ]:
# Storing the top 15 countries in a list
top_15_countries = list(freedom_index_df_top_15_2022['Countries'])
top_15_countries

['Hong Kong',
 'Singapore',
 'Switzerland',
 'New Zealand',
 'United States',
 'Denmark',
 'Ireland',
 'Canada',
 'Luxembourg',
 'Australia',
 'Japan',
 'United Kingdom',
 'Finland',
 'Iceland',
 'Malta']

In [ ]:
# Write the freedom_index_df dataframe to a csv file named 'freedom_index.csv'
freedom_index_df.to_csv('freedom_index.csv', index=False)