In [3]:
import pandas as pd

In [4]:
# Load the World Happiness Report data
df_happy = pd.read_excel('DataForTable2.1WHR2023.xls')

# Load the Economic Freedom Index data
df_free = pd.read_excel('economic-freedom-of-the-world-2024-master-index-data-for-researchers-iso.xlsx', header=4)

In [5]:
# Drop 'ISO Code 2' column and rename 'ISO Code 3' to 'Country Name'
df_free = df_free.drop(columns=['ISO Code 2'])
df_free = df_free.rename(columns={'ISO Code 3': 'Country Name'})

In [6]:
df_happy.head()

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.723590,7.350416,0.450662,50.500000,0.718114,0.167652,0.881686,0.414297,0.258195
1,Afghanistan,2009,4.401778,7.508646,0.552308,50.799999,0.678896,0.190809,0.850035,0.481421,0.237092
2,Afghanistan,2010,4.758381,7.613900,0.539075,51.099998,0.600127,0.121316,0.706766,0.516907,0.275324
3,Afghanistan,2011,3.831719,7.581259,0.521104,51.400002,0.495901,0.163571,0.731109,0.479835,0.267175
4,Afghanistan,2012,3.782938,7.660506,0.520637,51.700001,0.530935,0.237588,0.775620,0.613513,0.267919

In [7]:
df_free.head()

,Unnamed: 0,Year,Country Name,Countries,Economic Freedom Summary Index,Rank,Quartile,Government consumption,data,Transfers and subsidies,...,Tax compliance,Business regulations,Market openness,Business Permits,Distorton of the business environment,Freedom to enter markets and compete,Regulation,Area 5 Rank,World Bank Region,"World Bank Current Income Classification, 1990-Present"
0,NaN,2022.0,ALB,Albania,7.48,38.0,1.0,8.282353,11.84,7.133515,...,3.587625,5.379721,6.810619,5.621940,6.250000,6.227520,6.897016,55.0,Europe & Central Asia,UM
1,NaN,2022.0,DZA,Algeria,4.46,161.0,4.0,3.491176,28.13,7.817129,...,4.764764,3.841924,4.641448,8.771111,2.583207,5.331922,4.508463,156.0,Middle East & North Africa,LM
2,NaN,2022.0,AGO,Angola,4.79,155.0,4.0,7.944118,12.99,9.702997,...,4.641462,4.443797,3.427185,7.916416,1.250000,4.197867,5.302379,140.0,Sub-Saharan Africa,LM
3,NaN,2022.0,ARG,Argentina,4.55,159.0,4.0,6.167647,19.03,5.536785,...,4.504147,4.969248,6.144822,5.726521,3.380395,5.083913,4.804769,148.0,Latin America & the Caribbean,UM
4,NaN,2022.0,ARM,Armenia,7.49,36.0,1.0,7.058824,16.00,7.882834,...,6.020369,5.566860,5.590883,9.302574,5.000000,6.631152,7.095430,45.0,Europe & Central Asia,UM

In [8]:
req_columns_free = ['Year','Countries',' Economic Freedom Summary Index']
df_free = df_free[req_columns_free]

In [9]:
df_free.head()

     Year  Countries   Economic Freedom Summary Index
0  2022.0    Albania                             7.48
1  2022.0    Algeria                             4.46
2  2022.0     Angola                             4.79
3  2022.0  Argentina                             4.55
4  2022.0    Armenia                             7.49

In [10]:
req_columns_happy = ['Country name','year','Life Ladder','Healthy life expectancy at birth']
df_happy = df_happy[req_columns_happy]

In [11]:
df_happy.head()

  Country name  year  Life Ladder  Healthy life expectancy at birth
0  Afghanistan  2008     3.723590                         50.500000
1  Afghanistan  2009     4.401778                         50.799999
2  Afghanistan  2010     4.758381                         51.099998
3  Afghanistan  2011     3.831719                         51.400002
4  Afghanistan  2012     3.782938                         51.700001

In [12]:
# Display rows with missing 'Year' values
rows_with_nan = df_free[df_free['Year'].isna()]
print("Rows with missing 'Year':")
print(rows_with_nan)

# Drop rows with missing 'Year'
df_free = df_free.dropna(subset=['Year'])

Rows with missing 'Year':
      Year Countries   Economic Freedom Summary Index
4785   NaN       NaN                              NaN

In [13]:
df_free['Year'] = df_free['Year'].astype(int)

In [14]:
df_free.head()

   Year  Countries   Economic Freedom Summary Index
0  2022    Albania                             7.48
1  2022    Algeria                             4.46
2  2022     Angola                             4.79
3  2022  Argentina                             4.55
4  2022    Armenia                             7.49

In [15]:
df_happy.head()

  Country name  year  Life Ladder  Healthy life expectancy at birth
0  Afghanistan  2008     3.723590                         50.500000
1  Afghanistan  2009     4.401778                         50.799999
2  Afghanistan  2010     4.758381                         51.099998
3  Afghanistan  2011     3.831719                         51.400002
4  Afghanistan  2012     3.782938                         51.700001

In [16]:
merged_df = pd.merge(df_free,df_happy,left_on=['Year','Countries'],right_on=['year','Country name'],how='inner')

In [17]:
# Display first few rows of the merged dataset
merged_df.head()

,Year,Countries,Economic Freedom Summary Index,Country name,year,Life Ladder,Healthy life expectancy at birth
0,2022,Albania,7.48,Albania,2022,5.212213,69.175003
1,2022,Argentina,4.55,Argentina,2022,6.260993,67.250000
2,2022,Armenia,7.49,Armenia,2022,5.381943,67.925003
3,2022,Australia,7.98,Australia,2022,7.034696,71.125000
4,2022,Austria,7.62,Austria,2022,6.998997,71.275002

In [18]:
merged_df.columns

Index(['Year', 'Countries', ' Economic Freedom Summary Index', 'Country name',
       'year', 'Life Ladder', 'Healthy life expectancy at birth'],
      dtype='object')

In [19]:
merged_df.drop(columns=['Country name','year'],inplace=True)
merged_df.head()

,Year,Countries,Economic Freedom Summary Index,Life Ladder,Healthy life expectancy at birth
0,2022,Albania,7.48,5.212213,69.175003
1,2022,Argentina,4.55,6.260993,67.250000
2,2022,Armenia,7.49,5.381943,67.925003
3,2022,Australia,7.98,7.034696,71.125000
4,2022,Austria,7.62,6.998997,71.275002

In [20]:
merged_df.rename(columns={' Economic Freedom Summary Index':'Economic Freedom Index'},inplace=True)

In [21]:
eco_hap_df = merged_df.iloc[:]
eco_hap_df

,Year,Countries,Economic Freedom Index,Life Ladder,Healthy life expectancy at birth
0,2022,Albania,7.48,5.212213,69.175003
1,2022,Argentina,4.55,6.260993,67.250000
2,2022,Armenia,7.49,5.381943,67.925003
3,2022,Australia,7.98,7.034696,71.125000
4,2022,Austria,7.62,6.998997,71.275002
...,...,...,...,...,...
1891,2005,Romania,7.20,5.048648,64.500000
1892,2005,Saudi Arabia,5.39,7.079644,61.200001
1893,2005,Spain,7.88,7.152786,70.400002
1894,2005,Sweden,7.90,7.376316,71.000000
1895,2005,United Kingdom,8.34,6.983557,69.099998

In [22]:
eco_hap_df.isna().sum()

Year                                 0
Countries                            0
Economic Freedom Index              11
Life Ladder                          0
Healthy life expectancy at birth     0
dtype: int64

In [23]:
eco_hap_df[eco_hap_df['Economic Freedom Index'].isna()]

,Year,Countries,Economic Freedom Index,Life Ladder,Healthy life expectancy at birth
777,2016,Somalia,NaN,4.667941,48.500000
898,2015,Somalia,NaN,5.353645,48.099998
1021,2014,Somalia,NaN,5.528273,47.660000
1185,2012,Comoros,NaN,3.955640,57.480000
1307,2011,Comoros,NaN,3.838486,57.240002
1313,2011,Djibouti,NaN,4.369194,55.080002
1429,2010,Comoros,NaN,3.812191,57.000000
1435,2010,Djibouti,NaN,5.005811,54.599998
1530,2009,Comoros,NaN,3.476027,56.759998
1535,2009,Djibouti,NaN,4.905925,54.119999
1632,2008,Djibouti,NaN,5.009330,53.639999

In [24]:
eco_hap_df.dropna(inplace=True)

In [25]:
eco_hap_df.isna().sum()

Year                                0
Countries                           0
Economic Freedom Index              0
Life Ladder                         0
Healthy life expectancy at birth    0
dtype: int64

In [26]:
eco_hap_df_2022 = eco_hap_df[eco_hap_df['Year']==2022]

In [27]:
eco_hap_df_2022

,Year,Countries,Economic Freedom Index,Life Ladder,Healthy life expectancy at birth
0,2022,Albania,7.48,5.212213,69.175003
1,2022,Argentina,4.55,6.260993,67.250000
2,2022,Armenia,7.49,5.381943,67.925003
3,2022,Australia,7.98,7.034696,71.125000
4,2022,Austria,7.62,6.998997,71.275002
...,...,...,...,...,...
94,2022,United Kingdom,7.88,6.721780,70.400002
95,2022,United States,8.09,6.692790,65.724998
96,2022,Uruguay,7.04,6.670853,67.500000
97,2022,Vietnam,6.23,6.266509,65.599998
98,2022,Zimbabwe,3.53,3.296220,54.525002

In [28]:
eco_hap_df_2022_sorted = eco_hap_df_2022.sort_values(by='Economic Freedom Index',ascending=False)
eco_hap_df_2022_sorted

,Year,Countries,Economic Freedom Index,Life Ladder,Healthy life expectancy at birth
87,2022,Switzerland,8.43,6.883844,73.099998
70,2022,New Zealand,8.39,6.974987,70.425003
95,2022,United States,8.09,6.692790,65.724998
23,2022,Denmark,8.02,7.544965,71.375000
43,2022,Ireland,8.02,6.869864,71.400002
...,...,...,...,...,...
28,2022,Ethiopia,5.24,3.628072,61.099998
92,2022,Ukraine,5.12,4.637436,64.675003
15,2022,Chad,5.05,4.396646,53.125000
1,2022,Argentina,4.55,6.260993,67.250000
98,2022,Zimbabwe,3.53,3.296220,54.525002

In [29]:
eco_hap_df_top_20 = eco_hap_df_2022_sorted.iloc[:20,:]

In [30]:
eco_hap_df_top_20.reset_index(drop=True,inplace=True)
eco_hap_df_top_20

,Year,Countries,Economic Freedom Index,Life Ladder,Healthy life expectancy at birth
0,2022,Switzerland,8.43,6.883844,73.099998
1,2022,New Zealand,8.39,6.974987,70.425003
2,2022,United States,8.09,6.692790,65.724998
3,2022,Denmark,8.02,7.544965,71.375000
4,2022,Ireland,8.02,6.869864,71.400002
5,2022,Canada,7.99,6.917935,71.449997
6,2022,Luxembourg,7.98,7.227935,71.675003
7,2022,Australia,7.98,7.034696,71.125000
8,2022,Japan,7.90,6.178010,74.474998
9,2022,United Kingdom,7.88,6.721780,70.400002
10,2022,Finland,7.87,7.728998,71.224998
11,2022,Iceland,7.84,7.448794,72.074997
12,2022,Malta,7.82,6.299238,71.650002
13,2022,Germany,7.80,6.608207,71.500000
14,2022,Mauritius,7.79,5.740501,63.825001
15,2022,Netherlands,7.74,7.389636,71.625000
16,2022,Estonia,7.67,6.357114,69.875000
17,2022,Georgia,7.66,5.292755,65.074997
18,2022,Czechia,7.65,6.695077,69.175003
19,2022,Panama,7.62,5.979382,69.000000

In [32]:
df_epi = pd.read_excel('YALE-EPI.xlsx')

In [33]:
df_epi

,Economy ISO3,Economy Name,Indicator ID,Indicator,Attribute 1,Attribute 2,Attribute 3,Partner,1995,1996,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,ABW,Aruba,YALE.EPI.BCA,Environmental Performance Index: Adjusted emis...,-,-,-,-,100.00,100.00,...,64.02,60.39,65.89,68.86,63.70,65.09,58.52,58.52,58.52,58.52
1,ABW,Aruba,YALE.EPI.BHV,Environmental Performance Index: Biodiversity ...,-,-,-,-,39.91,39.91,...,39.91,39.91,39.91,39.91,39.91,39.91,39.91,39.91,39.91,39.91
2,ABW,Aruba,YALE.EPI.CDA,Environmental Performance Index: Adjusted emis...,-,-,-,-,10.59,10.59,...,63.76,81.12,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00
3,ABW,Aruba,YALE.EPI.CHA,Environmental Performance Index: Adjusted emis...,-,-,-,-,0.00,0.00,...,72.62,66.94,70.99,85.83,100.00,100.00,100.00,100.00,100.00,100.00
4,ABW,Aruba,YALE.EPI.COE,Environmental Performance Index: CO exposure,-,-,-,-,80.19,80.19,...,84.92,88.17,85.51,84.52,82.91,86.90,86.36,86.36,86.36,86.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10089,ZWE,Zimbabwe,YALE.EPI.VOE,Environmental Performance Index: VOC exposure,-,-,-,-,17.12,17.12,...,16.80,18.71,11.85,14.77,21.75,17.37,17.73,17.73,17.73,17.73
10090,ZWE,Zimbabwe,YALE.EPI.WMG,Environmental Performance Index: Waste Management,-,-,-,-,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.30
10091,ZWE,Zimbabwe,YALE.EPI.WRS,Environmental Performance Index: Water Resources,-,-,-,-,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.20
10092,ZWE,Zimbabwe,YALE.EPI.WTL,Environmental Performance Index: Wetland loss,-,-,-,-,100.00,100.00,...,22.57,40.38,40.38,35.05,28.22,27.67,28.83,28.83,28.83,28.83
10093,ZWE,Zimbabwe,YALE.EPI.WWT,Environmental Performance Index: Wastewater tr...,-,-,-,-,37.19,37.19,...,37.19,37.19,37.19,37.19,37.19,37.19,37.19,37.19,37.19,37.19